# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\denis\Desktop\QTapiBUN\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import test


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1059, 677)
        Widget.setStyleSheet("background-color: rgb(145, 0, 0);")

        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setObjectName("widget")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(340, 220, 331, 71))
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 300, 581, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(660, 370, 131, 29))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.MWclicked)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "News Generator"))
        self.label.setText(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Insert your API here:</span></p></body></html>"))
        self.pushButton.setText(_translate("Widget", "Generate news"))
   
    def MWclicked(self):
        import sys
        Link=self.lineEdit.text()
        Articole=test.PrelucrareData.APIdata("New API",Link)
        Articole.CreateAllYouNeed()
        app = test.QApplication(sys.argv)
        Widget = test.QWidget()
        ui = test.Ui_Widget()
        ui.setupUi(Widget,Articole.nrArticole,Articole)
        Widget.show()
        sys.exit(app.exec())

    
        

